name=OLED_Minima
version=1.0.2
author=DeepByte1
maintainer=DeepByte1
sentence=Ultra-lightweight SSD1306 OLED driver (8x8 font, ~1.7kB Flash, 0 RAM).
paragraph=This library works without buffers, sending data directly to the display. Perfect for ATTiny or low-memory projects.
category=Display
url=https://github.com
architectures=*