name=OLED_Minima
version=1.0.3
author=DeepByte1
maintainer=DeepByte1
sentence=Ultra-lightweight SSD1306 OLED driver (Untested flash (~1.7kB Flash at using 8x8 font, 8x5 untested), 0 RAM).
paragraph=This library works without buffers, sending data directly to the display. Perfect for ATTiny or low-memory projects.
category=Display
url=https://github.com/DeepByte1/OLED_Minima/
architectures=*

